[build]
  publish = "."
  command = ""

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "apiKey"
  SECRETS_SCAN_ENABLED = "false"

[[redirects]]
  from = "/games"
  to = "/games.html"
  status = 200

[[redirects]]
  from = "/games/*"
  to = "/games.html"
  status = 200

[[headers]]
  for = "/*.html"
    [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
