[build]
  publish = "."

[[redirects]]
  from = "/games"
  to = "/games.html"
  status = 200

[[redirects]]
  from = "/games/*"
  to = "/games.html"
  status = 200

[[headers]]
  for = "/*.html"
    [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/games.html"
    [headers.values]
    Cache-Control = "no-cache"
